FROM nvidia/cuda:12.3.0-base-ubuntu22.04 

ENV DEBIAN_FRONTEND=noninteractive 


RUN apt-get update && apt-get install -y \
    git \
    curl \
    build-essential \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt-get update


WORKDIR /code

#Install python3.12
RUN apt-get install -y python3.12 
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12
RUN apt-get update && apt-get install -y python3-pip


RUN python3.12 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
RUN git clone https://github.com/Ayrsz/UAED_Octave.git .

# Demais dependências
RUN python3.12 -m pip install \
    matplotlib \
    imageio \
    scipy \
    numpy==1.26.4 \
    "opencv-python-headless<4.10" \
    efficientnet-pytorch \
    wandb


CMD ["/bin/bash"]

#RUN python3.12 train_uaed.py